### ISSUE TITLE
how to return base64

### ISSUE THREAD

**Issue by wcjord** [googleapis/nodejs-text-to-speech#10]
I'd like to get the audio directly from the API in base64. This seems possible from the documentation and like it should happen when running the code below but the result isn't in base64. I imagine there's a way to specify this in audioConfig but I can't figure out how. I've tried each of the audioEncoding options.

#### Environment details

  - OS: Windows 10
  - Node.js version: v8.6.0
  - npm version: 5.3.0
  - `text-to-speech` version: 0.1.0

#### Steps to reproduce

  1.  Call the API with:
####
var request = {
                input: {
                    text: "this is just text"
                },
                voice: {
                    'languageCode': 'en-US',
                    'name': 'en-US-Wavenet-A',
                    'ssmlGender': 'MALE'
                },
                audioConfig: {
                    'audioEncoding': 'MP3'
                }
            };
            client.synthesizeSpeech(request, (err, response) => {
####
  2. Result is:
####
{ audioContent: <Buffer 4f 67 67 53 00 02 00 00 00 00 0
0 00 00 00 00 00 00 00 00 00 00 00 43 5e c1 a1 01 13 4f 70 75 73 48 65 61 64 01
01 38 01 c0 5d 00 00 00 00 00 4f 67 67 ...
####

Thanks!

**Comment by kinwa91** [comment]
Does manually calling `.toString('base64')` on the response buffer work?

**Comment by stephenplusplus** [comment]
I believe `.toString('base64')` should do it. Let us know if you still have any issues with this. Sorry for the slow reply!
