### ISSUE TITLE
I can't run successfully when I change my computer.

### ISSUE THREAD

**Issue by ibeeger** [googleapis/nodejs-text-to-speech#162]
<pre>GOOGLE_APPLICATION_CREDENTIALS=/Users/cxhmacbook/Documents/npms/recordChrome/test/auth.json node savemp3.js</pre>  
this code can save a mp3 file;

node v10.13.0  
npm v6.4.1

the same code and files  move to an other macbook can not run success~~!

**Comment by ibeeger** [comment]
may be  i am in Beijing, i can not  use google cloud service

**Comment by JustinBeckwith** [comment]
Greetings!  Happy to help! 
- When you run your code on your macbook - are you getting some kind of error?
- Are both machines running node 10.x?

**Comment by ibeeger** [comment]
> Greetings! Happy to help!
> 
> * When you run your code on your macbook - are you getting some kind of error?
> * Are both machines running node 10.x?

yes ,  I think  is network problems   when I open vpn  I  can  get results successfull, 
thanks . 
one in company  and other one macbook  in my home

**Comment by JustinBeckwith** [comment]
Got it.  Well it sounds like you have things figured out :) Let me know if there's anything else we can do to help!
