### ISSUE TITLE
metadata cue points.

### ISSUE THREAD

**Issue by synaptek** [googleapis/nodejs-text-to-speech#19]
I don't know if this is possible at the moment.  It would be highly valuable to have the ability to insert SSML metadata elements that would produce timed utterance-relative cue points (in a header or a separate file).  The goal is to be able to fire content sensitive events during an utterance.  Embedding would allow cues that track changes in the content automatically.  

Thanks

**Comment by nnegrey** [comment]
Hi, are you referring to something like this?
https://cloud.google.com/text-to-speech/docs/ssml

**Comment by nnegrey** [comment]
Oh like the time offset of each word utterance? Yea, it's currently not supported.
