### ISSUE TITLE
Only getting the audio of the last request when doing multiple requests at once

### ISSUE THREAD

**Issue by jvandenaardweg** [googleapis/nodejs-text-to-speech#210]
When doing multiple requests at once, using `Promise.all`, I seem to only get the `audioContent` of the last resolving request. It seems like the underlying code the library uses cannot handle concurrent requests?

I'm synthesizing large text's and need to split it up using the API's character limit. I had this working before, so I know it should work, but stopped working recently.

Am I doing something wrong here? Or is this a bug?

I'm doing the exact same with Amazon's Polly, and there it works. It's exactly the same code, but with a different client and different request options.

So that made me think maybe it's a library thing? Or a Google service issue?

#### Environment details

  - OS: Mac
  - Node.js version: 10.15.0
  - npm version: 6.8.0
  - `@google-cloud/text-to-speech` version: 0.5.1

#### Steps to reproduce
```typescript
export const googleSsmlToSpeech = async (
  index: number,
  ssmlPart: string,
  type: SynthesizerType,
  identifier: string,
  synthesizerOptions: GoogleSynthesizerOptions,
  storageUploadPath: string
) => {
  let extension = 'mp3';

  if (synthesizerOptions.audioConfig.audioEncoding === 'OGG_OPUS') {
    extension = 'opus';
  }

  if (synthesizerOptions.audioConfig.audioEncoding === 'LINEAR16') {
    extension = 'wav';
  }

  synthesizerOptions.input.ssml = ssmlPart;

  const tempLocalAudiofilePath = `${appRootPath}/temp/${storageUploadPath}-${index}.${extension}`;

  try {
    // Make sure the path exists, if not, we create it
    await fsExtra.ensureFile(tempLocalAudiofilePath);

      // Performs the Text-to-Speech request
    const [response] = await client.synthesizeSpeech(synthesizerOptions);

    // Write the binary audio content to a local file
    await fsExtra.writeFile(tempLocalAudiofilePath, response.audioContent, 'binary');

    return tempLocalAudiofilePath;
  } catch (err) {
    throw err;
  }
};

/**
 * Synthesizes the SSML parts into seperate audiofiles
 */
export const googleSsmlPartsToSpeech = async (
  ssmlParts: string[],
  type: SynthesizerType,
  identifier: string,
  synthesizerOptions: GoogleSynthesizerOptions,
  storageUploadPath: string
) => {
  const promises: Promise<string>[] = [];
  
  // Overwrite for demo purposes
  ssmlParts = [
    '<speak><p>this</p></speak>',
    '<speak><p>is a</p></speak>',
    '<speak><p>bit of a longer test</p></speak>'
  ];

  ssmlParts.forEach((ssmlPart: string, index: number) => {
    promises.push(googleSsmlToSpeech(index, ssmlPart, type, identifier, synthesizerOptions, storageUploadPath));
  });

  const tempAudioFiles = await Promise.all(promises);

  tempAudioFiles.sort((a: any, b: any) => b - a); // Sort: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 etc...

  return tempAudioFiles;
};
```

The above code creates multiple files with the correct naming and index number, however, they all contain the same audio. That is; the audio response of the last request (`<speak><p>bit of a longer test</p></speak>`).

```
824163ed-b4d9-4830-99da-6e6f985727e2-0.mp3
824163ed-b4d9-4830-99da-6e6f985727e2-1.mp3
824163ed-b4d9-4830-99da-6e6f985727e2-2.mp3
```

Replacing the `Promise.all` with a simple `for` loop, makes it work. But this takes longer as it waits for every request to resolve. I know a `Promise.all` can work, because I had it working before.

```typescript
  const tempAudioFiles = [];
  for (var i = 0; i < ssmlParts.length; i++) {
    tempAudioFiles[i] = await googleSsmlToSpeech(i, ssmlParts[i], type, identifier, synthesizerOptions, storageUploadPath);
  }
```

edit: updated the title and first paragraph with new findings. It seems to always return just the last one, even if it contains more text/audio then the other requests.

**Comment by jvandenaardweg** [comment]
Ok, so the API seems to be able to handle concurrent requests. Using the http endpoint with an API key seems to work fine.

```typescript
export const fetchSsmlPartToSpeech = (
  index: number,
  ssmlPart: string,
  type: SynthesizerType,
  identifier: string,
  synthesizerOptions: GoogleSynthesizerOptions,
  storageUploadPath: string
): Promise<string> => {
  return new Promise(async (resolve, reject) => {
    let extension = 'mp3';

    if (synthesizerOptions.audioConfig.audioEncoding === 'OGG_OPUS') {
      extension = 'opus';
    }

    if (synthesizerOptions.audioConfig.audioEncoding === 'LINEAR16') {
      extension = 'wav';
    }

    synthesizerOptions.input.ssml = ssmlPart;

    const tempLocalAudiofilePath = `${appRootPath}/temp/${storageUploadPath}-${index}.${extension}`;

    // Make sure the path exists, if not, we create it
    fsExtra.ensureFileSync(tempLocalAudiofilePath);

    try {
      const response = await nodeFetch('https://texttospeech.googleapis.com/v1/text:synthesize', {
        method: 'POST',
        body: JSON.stringify(synthesizerOptions),
        headers: {
          'Content-Type': 'application/json',
          'X-Goog-Api-Key': 'YOUR_GOOGLE_CLOUD_API_KEY'
        }
      })
      .then(response => response.json());

      const buff = new Buffer(response.audioContent, 'base64');

      await fsExtra.writeFile(tempLocalAudiofilePath, buff, 'binary');

      return resolve(tempLocalAudiofilePath);
    } catch (err) {
      console.log('Err fetch', err);
      return reject(err);
    }
  });
};
```

```typescript
ssmlParts.forEach((ssmlPart: string, index: number) => {
    promises.push(fetchSsmlPartToSpeech(index, ssmlPart, type, identifier, synthesizerOptions, storageUploadPath));
  });
```

So the problem seems related to the library itself...

**Comment by alexander-fenster** [comment]
Greetings @jvandenaardweg,

To make your code work in asynchronous way, you need to copy the request object for each call. Right now all invocations of `fetchSsmlPartToSpeech` reuse the same `synthesizerOptions` object so the `input` field gets overwritten when you do `synthesizerOptions.input.ssml = ssmlPart`, and as a result, the last assignment seems to be executed earlier than the first Text-to-Speech API call.

Long story short, this fix will make it work:

```sh
npm install --save lodash.merge
npm install --save-dev @types/lodash.merge
```

```ts
import merge = require('lodash.merge');

// later in the code
ssmlParts.forEach((ssmlPart: string, index: number) => {
  const opts = merge({}, synthesizerOptions);
  promises.push(fetchSsmlPartToSpeech(index, ssmlPart, type, identifier, opts, storageUploadPath));
});
```

Let us know if anything does not work!

**Comment by jvandenaardweg** [comment]
Hi @alexander-fenster, thanks for looking into it!

But then again, it's weird. I've checked what goes into `await client.synthesizeSpeech(synthesizerOptions)`, and that contains the correct SSML (the SSML part/chunk).

I'll try and fork the repo and see if I can add a new sample demonstration the problem.

**Comment by jvandenaardweg** [comment]
Hmm shit @alexander-fenster , you were right 👍

```
ssmlParts.forEach((ssmlPart: string, index: number) => {
  const ssmlPartSynthesizerOptions = Object.assign({}, synthesizerOptions);
  promises.push(fetchSsmlPartToSpeech(index, ssmlPart, type, identifier, ssmlPartSynthesizerOptions, storageUploadPath));
});
```

Did the trick. No need for lodash :-)

**Comment by alexander-fenster** [comment]
So what happens is that the API method you're calling (`client.synthesizeSpeech`) is asynchronous inside (makes several network calls and uses promises). It's likely that it yields the control flow before the actual request is sent to the server over gRPC, and this yielding is enough for the outer `forEach` loop to reassign the request parameter. You should not expect that your request parameter will be sent to the server right away without a context switch. Using unique object for each request is the best option.

Thanks!

**Comment by jvandenaardweg** [comment]
Thanks for the explanation!

Maybe a good thing to update the docs, samples or code with this? As it is quite normal to assume that the options you put in, is always what you get out of the API.

Probably something like this:

`options = Object.assign({}, options) || {};`

```javascript
synthesizeSpeech(request, options, callback) {
  if (options instanceof Function && callback === undefined) {
    callback = options;
    options = {};
  }
  options = Object.assign({}, options) || {};

  return this._innerApiCalls.synthesizeSpeech(request, options, callback);
}
```

https://github.com/googleapis/nodejs-text-to-speech/blob/master/src/v1/text_to_speech_client.js#L283

**Comment by alexander-fenster** [comment]
This is the repro that shows the problem:

```js
const fs = require('fs');
const textToSpeech = require('@google-cloud/text-to-speech');
const client = new textToSpeech.TextToSpeechClient();
const request = {
  input: {text: 'Original input'},
  voice: {languageCode: 'en-US', ssmlGender: 'NEUTRAL'},
  audioConfig: {audioEncoding: 'MP3'},
};

// fire the request!
const promise = client.synthesizeSpeech(request);

// immediately update request object
request.input.text = 'Updated input';

// get results
promise.then(response => {
  fs.writeFile('output.mp3', response[0].audioContent, 'binary', 
               (err) => { if (err) { console.error(err); } });
});  // will have 'Updated input'
```

Internally, this happens because of complicated logic inside `synthesizeSpeech` (caused by authentication). We are working on an update to our client libraries that will change the logic of the API methods so that this problem will likely disappear (there won't be a context switch in the place it happens now). Until that update is released (which will likely happen within next few months), please make sure you copy parameters.

**Comment by alexander-fenster** [comment]
To give you even more details, in Node the resolution of the promise is always asynchronous: in `promise.then(func)`, `func` will be always executed after `then()` returns, in the next tick.  To demonstrate:

```js
process.nextTick(() => { console.log('next tick happened'); });

const promise = Promise.resolve();
console.log('promise created');
promise.then(() => { console.log('promise resolved'); });
```

It will print `next tick happened` _before_ it prints `promise resolved`. Since we do have a promise and`.then()` in the method implenentation, this is where we yield the execution. We have a plan to change that.
