### ISSUE TITLE
Module `path` does not exist in the Haste module map

### ISSUE THREAD

**Issue by nileshprajapati007444** [googleapis/nodejs-text-to-speech#218]
After installing '@google-cloud/text-to-speech' package in react-native app. I got "Module `path` does not exist in the Haste module map".

#### Environment details

  - OS:
  - Node.js version: 
  - npm version: 6.9.0
  - `@google-cloud/text-to-speech` version: latest
- react-native version: 0.59.3

#### Steps to reproduce

 After installing this packge, i just import in App.js file like as below:
import { textToSpeech } from '@google-cloud/text-to-speech';

I am new in react-native. let me know if any other instruction missing to follow.
Please help me. Thanks in advance.

Thanks!

**Comment by callmehiphop** [comment]
Hi @nileshprajapati007444 these packages are built for Node.js and use a lot of the core modules that come with it. Unfortunately I don't think these modules are available in React Native applications, not by default at least. I think there is a plan for a client side version of the library, but I am pretty sure it is still a ways away.
