### ISSUE TITLE
How to use Wavenet voices

### ISSUE THREAD

**Issue by Xaviertoor** [googleapis/nodejs-text-to-speech#22]
I would like to use English (US) | WaveNet | en-US | en-US-Wavenet-F | FEMALE, but in code quickstart,js does not countain Voice name only languageCode code and ssmlGender.

```
// Select the language and SSML Voice Gender (optional)
    voice: {languageCode: 'en-US', ssmlGender: 'FEMALE'},
  // Select the type of audio encoding
  audioConfig: {audioEncoding: 'MP3'},
};
```

**Comment by Xaviertoor** [comment]
Resolved use the syntax below:
`// Select the language and SSML Voice Gender (optional)
  voice: {languageCode: 'en-US', name: 'en-US-Wavenet-F', ssmlGender: 'MALE'},
`

**Comment by tigco** [comment]
It seems using only voice: {name: 'en-US-Wavenet-F'} should be enough. Though, neither is working for me at the moment.
`
voice: {languageCode: 'en-US', name: 'en-US-Wavenet-F', ssmlGender: 'FEMALE'},
`
