### ISSUE TITLE
Google Text to Speech Emphasis on one word

### ISSUE THREAD

**Issue by vin-ni** [googleapis/nodejs-text-to-speech#237]
When I use the google speech to text api, I need a little more settings on the emphasis / pronunciation of words. In my case, I'd like to generate the name:

``` lang-html
Peter
``` 
as it is pronounced in the sentence 
``` lang-html
Peter, you know whats up.
``` 

but without generating the rest. I've tried experimenting with tags such as

``` lang-html
Peter <break strength="strong"/>
```

Any Ideas on how I could do that? Thanks!

  [1]: https://cloud.google.com/text-to-speech/?

**Comment by callmehiphop** [comment]
I'm not finding anything in the documentation that demonstrates how to do something like this, @nnegrey any ideas here?

**Comment by nnegrey** [comment]
Ah yea. So you want to look at the SSML format found here: https://cloud.google.com/text-to-speech/docs/ssml

But let me know if you need more help. 

Are you wrapping your whole text in a `<speak>` tag?

**Comment by vin-ni** [comment]
Yes, I've been studying this. I'm currently building a dynamic audio tool where I need to generate: Hello, [name], nice to meet you.
My Idea was to generate the static audio and to just generate the name on the go. But when I generate the name on its own, the result is completely different, as when it's generated with the matching sentence. This is correct behaviour, but in my case I'd need to add some setting to mimik the pronounciation the name would get if it was in a normal sentence.

**Comment by vin-ni** [comment]
Here are the two examples. One is "Peter" alone and the other is "Peter, you know what's up".
I'd need to generate "Peter" with the same pronunciation as in the long sentence.

[Archiv.zip](https://github.com/googleapis/nodejs-text-to-speech/files/3276995/Archiv.zip)

**Comment by nnegrey** [comment]
What are your voice selection params?

Using this one for example gives me the right results.
```
voice = texttospeech.types.VoiceSelectionParams(
        language_code='en-US',
        ssml_gender=texttospeech.enums.SsmlVoiceGender.FEMALE)
```
It's just very subtle.

**Comment by vin-ni** [comment]
What version are you using? 

I may be way behind, as I'm using ` "@google-cloud/text-to-speech": "^0.5.1"`
Is there a difference in quality between the versions, or are they always using the newest models?
I see your syntax is quite different.


``` javascript 
const textToSpeechrequestSSML = {
    input: {
        ssml: '<speak>Peter<speak>'
    },
    voice: {
        languageCode: 'de-DE',
        ssmlGender: 'MALE'
    },
    audioConfig: {
        audioEncoding: 'LINEAR16',
        bitrate: 96
    },
};
```

**Comment by nnegrey** [comment]
Oh so sorry, I've been jumping between languages and was testing in Python. However, the API will still return the same results. 

I would recommend using the latest library, but that shouldn't change the results.

I notice in the example code you posted above you don't include the `emphasis` tag in the SSML, but I'm guess you do when sending the actual request. 

```
const textToSpeechrequestSSML = {
    input: {
        ssml: '<speak><emphasis level="strong">Peter</emphasis><speak>'
    },
    voice: {
        languageCode: 'de-DE',
        ssmlGender: 'MALE'
    },
    audioConfig: {
        audioEncoding: 'LINEAR16',
    },
};
```

What's your `bitrate` field? I don't believe that is part of the API.

**Comment by vin-ni** [comment]
What do you mean with 

> will still return the same results. ?

The emphasis of the name is different depending on the following words, right? So 
`<speak><emphasis level="strong">Peter</emphasis><speak>`
 sounds different as the Peter in
`<speak><emphasis level="strong">Peter, what's up?</emphasis><speak> `
right?

**Comment by nnegrey** [comment]
The library version doesn't matter, because it's hitting the same backend API, so the result will be the same. 

It's likely that something spoken in a sentence is different than when spoken singularly.

**Comment by vin-ni** [comment]
Yes, I guessed that. I would need to somehow emulate that word being in that sentence, without having to generate the whole sentence. 

But probably it's not possible.

(Actually the bitrate parameter works, even if it's not documented)

**Comment by nnegrey** [comment]
Might be worth playing with the `<prosody>` element. 
https://www.w3.org/TR/speech-synthesis11/#S3.2.4

**Comment by nnegrey** [comment]
In the end, you can file a issue directly to the product team about the backend results on here: https://cloud.google.com/support/docs/issue-trackers
