### ISSUE TITLE
SynthesizeSpeech timeout when using ssml 

### ISSUE THREAD

**Issue by horbel** [googleapis/nodejs-text-to-speech#252]
Hi guys. The version of package 1.1.3.
08/14/2019 I noticed that requests through client.SynthesizeSpeech() failed by timeout. I sending parts of ssml with length 5000.

```
const request = {

                input: {ssml: someText},	              
                voice: languageConfig,	      
                audioConfig: {	                
                    audioEncoding: 'MP3',	                  
                    sampleRateHertz: 16000,	             
                    effectsProfileId: ['handset-class-device' ]
            }
```

Then I tried to send smaller pieces of ssml (2000 chars). And now I got the response but still, it works much slower than previous. Maybe be do you know what could be the reason of such behavior?  

Also I almost sure that   `input: {text: someText} ` works pretty much faster

Thanks in advance!

**Comment by jvandenaardweg** [comment]
I'm also experiencing the same, screenshot below is from Sentry, which is tracking errors in my app:

<img width="831" alt="Screenshot 2019-08-16 at 13 20 13" src="https://user-images.githubusercontent.com/5155373/63164410-a02c6680-c028-11e9-96fe-fd66d6b2cbb6.png">

**Comment by jvandenaardweg** [comment]
Well, that did not work. Same problem exists on 1.1.2. Seems the Google Text To Speech service has troubles then.

**Comment by AndreyPoznyak** [comment]
@jvandenaardweg as a temporary workaround try to switch to `text` from `ssml` - it works ok. You'll lose some functionality of course but see if it works for you till Google fixes its stuff

**Comment by jvandenaardweg** [comment]
Thanks, that's a nice little work-around for now @AndreyPoznyak 

Text requests seem to indeed have the performance like before.

Would definitely see the SSML problem be fixed, as I heavily rely on SSML

**Comment by bbookman** [comment]
Can someone on this thread get me code and sample SSML that reproduces the issue?  (I'm at Google)

**Comment by bbookman** [comment]
P.S.  If you have a Google support ticket number that will also help me investigate

**Comment by JustinBeckwith** [comment]
Greetings folks!  It sounds like the issue here is not related to the nodejs library, and is more a problem with the back end service.  We can send this to a few folks on that team - but it probably makes the most sense if you:
a.) If you have a support contract, make sure to file a ticket and
b.) File an issue in their issue tracker over here: https://issuetracker.google.com/savedsearches/559758

We can keep this open for tracking purposes, but I want to make sure y'all are getting in touch with the right team.

**Comment by AndreyPoznyak** [comment]
Hi guys
@bbookman @JustinBeckwith here is the ticket I reported a couple of days ago: https://issuetracker.google.com/issues/139429599

@bbookman any text wrapped in SSML's `<speak>` with length more than 3k chars and it reproduces - however, it definitely is not related to this nodejs lib as mentioned above

thanks!

**Comment by bbookman** [comment]
Thanks Andrey, I'll check it out and report back when I have anything

**Comment by jvandenaardweg** [comment]
Thanks @bbookman @JustinBeckwith @AndreyPoznyak 👍

**Comment by bbookman** [comment]
I can reproduce this.  Next stop is to get the issue to the right folks.

```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
```

**Comment by AdamSHurwitz** [comment]
Interesting note - I've refactored the 'synthesizeSpeech' method to use 'text' as the input instead of 'ssml', while leaving the '.ssml()' method at the end. The API appears to be converting the text with the higher Wavenet quality as opposed to the standard speech quality.

'input: { text: (new Speech).say(textFileData).ssml()}'

**Comment by jvandenaardweg** [comment]
Somebody already tried if it's working again? I haven't found the time yet to re-test

**Comment by AndreyPoznyak** [comment]
@jvandenaardweg yeah seems to be resolved already
