### ISSUE TITLE
How to use my own credential?

### ISSUE THREAD

**Issue by choongyouqi** [googleapis/nodejs-text-to-speech#26]
I'm hitting `Cloud Text-to-Speech API has not been used in project 563584335869 before or it is disabled` from the example. and interesting enough, `563584335869` is not one of my projects in `gcloud projects list`.

If we follow the [structure](https://github.com/googlecloudplatform/google-cloud-node#quick-start) of other `@google-cloud/*` apis, we should be able to pass in our `keyFile` as `config`:

```
var config = {
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
};
var datastore = require('@google-cloud/text-to-speech')(config);
```

but it doesn't seem to accept any parameter at the moment.

**Comment by JustinBeckwith** [comment]
Greetings!  The default export of the module is a class type, which needs to be instantiated.  For example:

```js
// Imports the Google Cloud client library
const textToSpeech = require('@google-cloud/text-to-speech');

// Create the auth config
const config = {
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
};

// Creates a client
const client = new textToSpeech.TextToSpeechClient(config);
```

Hope this helps!

**Comment by nicogon** [comment]
This should be included in the example

**Comment by lincolnlemos** [comment]
This should be included in the example 2x

**Comment by nolimitdev** [comment]
Now is 2022 and such as in 2018 in example is missing auth https://www.npmjs.com/package/@google-cloud/text-to-speech Is it possible dear Google? How we could know that code from example `new textToSpeech.TextToSpeechClient();` shout be `new textToSpeech.TextToSpeechClient(config);` ???
