### ISSUE TITLE
Unexpected error determining execution environment: network timeout

### ISSUE THREAD

**Issue by iMaximal** [googleapis/nodejs-text-to-speech#267]
OS: Windows 10 (last)
node: v12.10.0
npm: 6.11.3

Steps:
1. npm install @google-cloud/text-to-speech -S
2. Copy code from npm to index.js file
3. node index.js

`FetchError: Unexpected error determining execution environment: network timeout at: http://169.254.169.254/computeMetadata/v1/instance
    at Timeout.<anonymous> (D:\Projects\speech\node_modules\node-fetch\lib\index.js:1448:13)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  message: 'Unexpected error determining execution environment: network timeout at: http://169.254.169.254/computeMetadata/v1/instance',
  type: 'request-timeout',
  config: {
    url: 'http://169.254.169.254/computeMetadata/v1/instance',
    headers: { 'Metadata-Flavor': 'Google' },
    retryConfig: {
      noResponseRetries: 0,
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      httpMethodsToRetry: [Array],
      statusCodesToRetry: [Array]
    },
    responseType: 'text',
    timeout: 3000,
    params: [Object: null prototype] {},
    paramsSerializer: [Function: paramsSerializer],
    validateStatus: [Function: validateStatus],
    method: 'GET'
  }
}
`

Please, check the server and add credential support.

Thank you for your hard work!

**Comment by iMaximal** [comment]
Thank you!

I've read:
https://cloud.google.com/docs/authentication/getting-started#auth-cloud-implicit-nodejs

Created service account.
Save json as key.json in root folder
npm i -S cross-env
"start": "cross-env GOOGLE_APPLICATION_CREDENTIALS=key.json node index.js",

Profit.

Please, close.

**Comment by bcoe** [comment]
@iMaximal awesome 👍 glad you're unblocked.
