### ISSUE TITLE
Should we still have a smoke test?

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-text-to-speech#293]
As I understand it, with the monolith gapic generator we used to create this optional sorta smoke test.  We have one of those here:
https://github.com/googleapis/nodejs-text-to-speech/blob/master/smoke-test/text_to_speech_smoke_test.js

I don't think we generate these anymore.  should we just switch this to a system test?  Delete it?

**Comment by alexander-fenster** [comment]
I will move this to a system test. We are not going to generate those smoke tests by micro-generators.

**Comment by alexander-fenster** [comment]
This was moved to the system tests long ago. Closing.
