### ISSUE TITLE
TypeScript issue when creating client

### ISSUE THREAD

**Issue by benhjames** [googleapis/nodejs-text-to-speech#298]
Trying out the new TypeScript build results in a type error when creating the client:

```ts
import textToSpeech from '@google-cloud/text-to-speech';

const GOOGLE_CREDENTIAL_CLIENT_EMAIL = "...";
const GOOGLE_CREDENTIAL_PRIVATE_KEY = "...";

const textToSpeechClient = new textToSpeech.TextToSpeechClient({
  credentials: {
    client_email: GOOGLE_CREDENTIAL_CLIENT_EMAIL,
    private_key: GOOGLE_CREDENTIAL_PRIVATE_KEY,
  },
});
```

```
Argument of type '{ credentials: { client_email: string; private_key: string; }; }' is not assignable to parameter of type 'ClientOptions'.
  Type '{ credentials: { client_email: string; private_key: string; }; }' is missing the following properties from type 'ClientOptions': servicePath, port
```

Though it looks these properties are not required (or aren't documented) [as can be seen here](https://googleapis.dev/nodejs/text-to-speech/latest/v1.TextToSpeechClient.html).

Using `typescript@3.7.2`, `@google-cloud/text-to-speech@2.0.1`.

Perhaps I am setting it up incorrectly, please let me know! 👍

**Comment by bcoe** [comment]
@benhjames as a workaround, I recommend using a service account JSON file, and pointing to it with the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.

I agree that we should address this and make it easier to authenticate with a `private_key` (seems like an oversight in our types.

**Comment by alexander-fenster** [comment]
@benhjames It does not actually complain about your credentials object. It just wants you to pass `servicePart` and `port`. They are not supposed to be required (I'll fix that), but for now, just do this:

```ts
import {TextToSpeechClient} from '@google-cloud/text-to-speech';
  
const servicePath = TextToSpeechClient.servicePath;  // <--- default values are OK
const port = TextToSpeechClient.port;

const GOOGLE_CREDENTIAL_CLIENT_EMAIL = "...";
const GOOGLE_CREDENTIAL_PRIVATE_KEY = "...";

const textToSpeechClient = new TextToSpeechClient({
  credentials: {
    client_email: GOOGLE_CREDENTIAL_CLIENT_EMAIL,
    private_key: GOOGLE_CREDENTIAL_PRIVATE_KEY,
  },
  servicePath,   // <--- pass servicePath and port
  port
});

```
