### ISSUE TITLE
Typescript error  "Type 'string' is not assignable to type 'AudioEncoding'"

### ISSUE THREAD

**Issue by zipou** [googleapis/nodejs-text-to-speech#314]
#### Environment details

  - OS: OS X Catalina 10.15.2
  - Node.js version: v13.5.0
  - Typescript version: 3.7.2
  - npm version: 6.13.4
  - `@google-cloud/text-to-speech` version: 2.1.0

#### Steps to reproduce

I'm was using the demo code, which worked fine until I updated the library from 0.5^ to 2.1.^
```
import {TextToSpeechClient} from  '@google-cloud/text-to-speech'

  const client = new TextToSpeechClient({
    projectId: 'PROJECT_ID',
    keyFilename: googleKey,
  });

  // Construct the request
  const request = {
    input: {
      text: text
    },
    // Select the language and SSML Voice Gender (optional)
    voice: {
      languageCode: 'fr-FR',
      name: "fr-FR-Wavenet-A",
      ssmlGender: "NEUTRAL",
    },
    // Select the type of audio encoding
    audioConfig: {
      audioEncoding: 'LINEAR16',
      sampleRateHertz: 8000,
    },
  };

const response = await client.synthesizeSpeech(request);
```

But now with this code, Typescript is complaining :

Argument of type '{ input: { text: string; }; voice: { languageCode: string; name: string; }; audioConfig: { audioEncoding: string; sampleRateHertz: number; }; }' is not assignable to parameter of type 'ISynthesizeSpeechRequest'.
  The types of 'audioConfig.audioEncoding' are incompatible between these types.

Argument of type '{ input: { text: string; }; voice: { languageCode: string; name: string; ssmlGender: string; }; audioConfig: { sampleRateHertz: number; }; }' is not assignable to parameter of type 'ISynthesizeSpeechRequest'.
  The types of 'voice.ssmlGender' are incompatible between these types.
    Type 'string' is not assignable to type 'SsmlVoiceGender'.

I got it working with this :

```
import * as protos from "@google-cloud/text-to-speech/build/protos/protos"

const request = {
    input: {
      text: text
    },
    // Select the language and SSML Voice Gender (optional)
    voice: {
      languageCode: 'fr-FR',
      name: "fr-FR-Wavenet-A",
      ssmlGender: protos.google.cloud.texttospeech.v1.SsmlVoiceGender.NEUTRAL,
    },
    // Select the type of audio encoding
    audioConfig: {
      audioEncoding: protos.google.cloud.texttospeech.v1.AudioEncoding.LINEAR16,
      sampleRateHertz: 8000,
    },
  }
```

**Comment by bcoe** [comment]
@zipou thanks for the bug report 👍 @alexander-fenster sounds like a slight hiccup with our type generation potentially?

**Comment by alexander-fenster** [comment]
That's something with how `protobufjs` and its TypeScript converter `pbts` handles enums. The underlying serialization logic perfectly accepts strings but TypeScript forces it to be a proper enum value. I don't have a good idea of how to fix it so that everyone is happy but I'll think about it :)

**Comment by bcoe** [comment]
@alexander-fenster could we potentially classify this as a feature request rather than a bug, what do you think?

**Comment by danielgwilson** [comment]
FYI this also breaks your quickstarts—
(from https://cloud.google.com/text-to-speech/docs/quickstart-client-libraries)

```typescript
// Imports the Google Cloud client library
const textToSpeech = require('@google-cloud/text-to-speech');

// Import other required libraries
const fs = require('fs');
const util = require('util');
// Creates a client
const client = new textToSpeech.TextToSpeechClient();
async function quickStart() {

  // The text to synthesize
  const text = 'hello, world!';

  // Construct the request
  const request = {
    input: {text: text},
    // Select the language and SSML voice gender (optional)
    voice: {languageCode: 'en-US', ssmlGender: 'NEUTRAL'},
    // select the type of audio encoding
    audioConfig: {audioEncoding: 'MP3'},
  };

  // Performs the text-to-speech request
  const [response] = await client.synthesizeSpeech(request);
  // Write the binary audio content to a local file
  const writeFile = util.promisify(fs.writeFile);
  await writeFile('output.mp3', response.audioContent, 'binary');
  console.log('Audio content written to file: output.mp3');
}
quickStart();
```

**Comment by alexander-fenster** [comment]
@danielgwilson Quickstarts are in JS, not TS, and thus not broken :)  But good news is that it's fixed in #331 and will be released soon!

**Comment by alexander-fenster** [comment]
This fix was released, enums now accept strings.

**Comment by meowlanguages** [comment]
If somebody has any similar problems, below I posted some workaround, what I found on [https://westa.io/@alclimb/fp9o](https://westa.io/@alclimb/fp9o)

THANK TO AUTHOR, YOU SAVED MY LIFE
```
import dotenv from "dotenv"
import * as fs from "fs-extra"
import { TextToSpeechClient, protos } from "@google-cloud/text-to-speech"

dotenv.config({ path: `./.secrets/.env` })
main()

async function main() {
    const client = new TextToSpeechClient()
    const request: **protos.google.cloud.texttospeech.v1.ISynthesizeSpeechReques**t = {
        input: { text: `hello, world!` },

        voice: { languageCode: `en-US`, name: `en-US-Wavenet-D` },
        audioConfig: {
            audioEncoding: `MP3`,
            pitch: 0.00,
            speakingRate: 1.00
        },
    }
    const [response] = await client.synthesizeSpeech(request)
    fs.writeFileSync(`output.mp3`, response.audioContent, `binary`)

    console.log(`Audio content written to file: output.mp3`)
}
```
