### ISSUE TITLE
Transcription Expensive or running double?

### ISSUE THREAD

**Issue by vin-ni** [googleapis/nodejs-text-to-speech#316]
Hello,
I'm using node to send interviews to the text-to-speech api.
After transcribing 3 interviews of about 1 hour i now got billed about 14 Dollars. If i did my calculations right, this is about 3 times the price it should be.

Does anyone have an idea if there's a mistake in my code?

Bascially I'm doing the following from the user interface:
1. Upload the mp3 to my node server
2. Transfer the audiofile to a google cloud bucket 
3. Run `longRunningRecognize` on that file and return the result via socket to the client.

Here's my code:
``` javascript
client.on('startAnalyzing', function (data) {
        const gcsUri = data.gcsUri;
        const language = data.language;

        // async long audio
        async function recognizeFile() {
            console.log('started transcribing');
            // Creates a client
            const recognitionClient = new speech.SpeechClient();

            // The audio file's encoding, sample rate in hertz, and BCP-47 language code
            const audio = {
                uri: gcsUri,
            };
            const config = {
                encoding: 'MP3',
                sampleRateHertz: 16000,
                languageCode: language,
                enableAutomaticPunctuation: true,
                diarizationSpeakerCount: 2,
                enableWordTimeOffsets: true,
            };
            const request = {
                audio: audio,
                config: config,
            };

            const [operation] = await recognitionClient.longRunningRecognize(request); // log status? https://github.com/googleapis/nodejs-speech/issues/420
            // Get a Promise representation of the final result of the job
            const [response] = await operation.promise();

            let resultObj = {
                metadata: response.results
            }
            client.emit('transResult', resultObj);

            console.log(JSON.stringify(response.results));
        }


        async function run() {
            try {
                await recognizeFile();
            } catch (e) {
                console.error(e);
                client.emit('my error', "")
            } finally {
                console.log('done transcribing');
            }
        }

        run();
    });
```

Thanks a lot!

**Comment by vin-ni** [comment]
And is there any way to retrieve information on how many minutes have been transcribed per month, so I can check with how much i supposedly sent?

**Comment by bcoe** [comment]
Hey @vin-ni 👋 since this is partially a billing related question, it might be worth also opening an issue here:

https://issuetracker.google.com/savedsearches/5235428

Leaving this issue open as well 👍

**Comment by telpirion** [comment]
I think this is a question about [Node.js client library for Speech-to-Text](https://github.com/nodejs-speech/) rather than Text-to-Speech. You can see the pricing details for Speech-to-Text [here](https://cloud.google.com/speech-to-text/pricing).

If you are still experiencing this issue, please contact [Billing](https://cloud.google.com/support/billing).
