### ISSUE TITLE
Need React native module for text to speech

### ISSUE THREAD

**Issue by ykcadcg** [googleapis/nodejs-text-to-speech#326]
Apparently I couldn't just use 'google-cloud/text-to-speech' for my RN app: error:

Unable to resolve module `querystring` from `node_modules/google-gax/build/src/routingHeader.js`: querystring could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by b-loved-dreamer** [comment]
This issue may no longer be relevant so I am closing it. Please feel free to reopen.
