### ISSUE TITLE
progressive tts response

### ISSUE THREAD

**Issue by gchiocchio** [googleapis/nodejs-text-to-speech#381]
To create a personalized assistant such as an IVR it is necessary the TTS begins to speak before the file is downloaded. Otherwise there may be annoying latencies with the user.

An example can be: 

tts.synthesizeSpeech(params, (err, chunk) => {
    if (err) {
        console.log(err.code)
    } else if (chunk) {
        //chunk of wav to reproduce or save
    }
})

**Comment by bcoe** [comment]
@gchiocchio is this a feature request you have for the API?

**Comment by gchiocchio** [comment]
Yes is a features request. Thanks

Il Mar 7 Apr 2020, 08:39 Benjamin E. Coe <notifications@github.com> ha
scritto:

**Comment by b-loved-dreamer** [comment]
Thank you for your feature request. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing nodejs-text-to-speech. After careful consideration, we have decided not to proceed with this enhancement. If you disagree, please feel free to re-open this issue and explain why you believe it is essential for users of this client library.
