### ISSUE TITLE
timeout has no effect

### ISSUE THREAD

**Issue by videopuppet** [googleapis/nodejs-text-to-speech#394]
According to https://googleapis.dev/nodejs/text-to-speech/latest/v1.TextToSpeechClient.html#synthesizeSpeech and https://googleapis.github.io/gax-nodejs/interfaces/CallOptions.html, it should be possible to set a timeout; however the code seems to ignore that setting.

#### Environment details

  - OS: macOS 10.14.6
  - Node.js version: v12.16.1
  - npm version: 6.14.4
  - `@google-cloud/text-to-speech` version: 2.3.0

#### Steps to reproduce

  1. execute the following without a network connection, or simulate a long latency

```
const textToSpeech = require('@google-cloud/text-to-speech');
const client = new textToSpeech.TextToSpeechClient();
const [response] = await client.synthesizeSpeech(request, { timeout: 1 });
```

the request does not time out, but keeps waiting

**Comment by CRGer** [comment]
Hey, still facing that issue. Any solutions?

**Comment by munkhuushmgl** [comment]
@CRGer Have you tried the following?
```
      const options = {timeout: 180000};
      const [response] = await client. synthesizeSpeech(request, options);
```

**Comment by CRGer** [comment]
Hi @munkhuushmgl 
Tried a similar request with a lower timeout. But it stays with the default timeout of 600.000ms.

**Comment by munkhuushmgl** [comment]
Ok, Then lemme try it on my end, and come back to you.

**Comment by CRGer** [comment]
Thank you!

**Comment by CRGer** [comment]
Additionial issue:
That is the error message after a default timeout: "Total timeout of API google.cloud.texttospeech.v1.TextToSpeech exceeded 600000 milliseconds before any response was received."
After several tests, I noticed that the time varies, and does not match 600.000ms. On average, the timout occurs after about 630.000ms, but with many deviations.

**Comment by b-loved-dreamer** [comment]
Hi. I would recommend researching our docs in order to find the right syntax for this task. Here is a [reference](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.TextToSpeech.V1/api/Google.Cloud.TextToSpeech.V1.TextToSpeechSettings.html). I am now closing this issue. Feel free to reopen.

**Comment by CRGer** [comment]
Hi @b-loved-dreamer 
I can't find anything in the mentioned docs, this might be helpful. While searching the docs before, I found the syntax which was also mentioned in this ticket.
