### ISSUE TITLE
API key usage

### ISSUE THREAD

**Issue by uev1** [googleapis/nodejs-text-to-speech#399]
In Quickstart sample, user have to define a venv in the system in order to use TTS API, isn't there any way to directly use an API key directly generated in Cloud Console regardless of security concerns ?

**Comment by UnsolvedCypher** [comment]
Yes, there is. When you create the client, pass a credentials object like this:

```
const client = new textToSpeech.TextToSpeechClient({
  credentials: { 
    client_email: 'your-client-email@something.iam.gserviceaccount.com', 
    private_key: '-----BEGIN PRIVATE KEY-----\n{your-private-key}\n-----END PRIVATE KEY-----\n' },
});
```

**Comment by giorgosera** [comment]
I believe this should be in the documentation!

**Comment by telpirion** [comment]
Hello @giorgosera , using API keys is considered an [anti pattern](https://cloud.google.com/docs/authentication/production#best_practices) for development on Google Cloud. We don't document the use of API keys for this very reason.
