### ISSUE TITLE
Wix Integration

### ISSUE THREAD

**Issue by lobointerestelar** [googleapis/nodejs-text-to-speech#404]
If there is a way to integrate the nodejs-text-to-speech to wix?
How could be possible only to listen the speech result without generate an mp3 file?
Thanks.

**Comment by bcoe** [comment]
@lobointerestelar your best bet would probably be to look at using Google Cloud Functions, or Cloud Run, to run a service that performs the text to speech translation, and then have your Wix site call that endpoint.

We do not have a direct integration with Wix.

**Comment by lobointerestelar** [comment]
Thank you @bcoe for you answer, actually I already found a solution using nodejs, google cloud text to speech, Corvid and html element with html and CSS.

**Comment by bcoe** [comment]
@lobointerestelar awesome, I'm glad you're unblocked 👍
