### ISSUE TITLE
Missing support for  Google SSML <mark>

### ISSUE THREAD

**Issue by chanind** [googleapis/nodejs-text-to-speech#410]
Google cloud's TTS supports the SSML `<mark />` tag, as specified in the docs at https://cloud.google.com/text-to-speech/docs/ssml#mark. However, using this node library there's no way to access the timestamps of these `<mark />` tags. Responses always contain only an `audioContent` property, with no way to retrieve the timestamps of the `<mark />` tags added to SSML.

**Comment by b-loved-dreamer** [comment]
Please check the latest version of the library for new features. I am now closing this issue. Feel free to reopen.

**Comment by alexyoux** [comment]
It is still not returning the info. Only audioContent is returned. I just check with the latest version. can you help out? thanks
