### ISSUE TITLE
Documentation WaveNet vs. Standard voices

### ISSUE THREAD

**Issue by jzombie** [googleapis/nodejs-text-to-speech#452]
The documentation doesn't make it very apparent as to if this is using the standard voice or the WaveNet voice, and I think it should be clearly labeled, especially since there is a 4x price increase for WaveNet over standard.

`
 // Construct the request
  const request = {
    input: {text: text},
    // Select the language and SSML voice gender (optional)
    voice: {languageCode: 'en-US', ssmlGender: 'NEUTRAL'},
    // select the type of audio encoding
    audioConfig: {audioEncoding: 'MP3'},
  };
`

A good fix would be to show examples of how this is achieved, right here in the README.md.

**Comment by joshuacrowley** [comment]
Hi, it would be fantastic to get more documentation how to use the WaveNet voices with the Node SDK (3.2.2). The following seems to still produce Standard voices, as far as my ear can tell.

```

// Imports the Google Cloud client library
const textToSpeech = require("@google-cloud/text-to-speech");

// Import other required libraries
const fs = require("fs");
const util = require("util");
// Creates a client
const client = new textToSpeech.v1beta1.TextToSpeechClient();
async function quickStart() {
  // The text to synthesize
  const text = "hello, world!";

  // Construct the request
  const request = {
    input: { text: text },
    // Select the language and SSML voice gender (optional)
    voice: {
      languageCode: "en-AU",
      ssmlGender: "FEMALE",
      name: "en-AU-Wavenet-C",
    },
    // select the type of audio encoding
    audioConfig: {
      effectsProfileId: ["headphone-class-device"],
      audioEncoding: "MP3",
    },
  };

  // Performs the text-to-speech request
  const [response] = await client.SynthesizeSpeechRequest(request);
  // Write the binary audio content to a local file
  const writeFile = util.promisify(fs.writeFile);
  await writeFile("output.mp3", response.audioContent, "binary");
  console.log("Audio content written to file: output.mp3");
}
quickStart();

```

**Comment by telpirion** [comment]
Selecting a voice by its ID is as simple as the snippet provided by @joshuacrowley . You set the `Voice.name` field to the ID of the voice you want.

* To find the ID of Standard voices, see here: https://cloud.google.com/text-to-speech/docs/voices
* To understand how to use the `Voice.name` field, see here: https://googleapis.dev/nodejs/text-to-speech/latest/google.cloud.texttospeech.v1beta1.IVoice.html

**Comment by telpirion** [comment]
You can also learn more about WaveNet voices here:

https://cloud.google.com/text-to-speech/docs/wavenet
