### ISSUE TITLE
Not all SSML marks get corresponding timepoints

### ISSUE THREAD

**Issue by infation** [googleapis/nodejs-text-to-speech#470]
Hi,

I have been trying to get the <mark> tags working, but not all of them get the corresponding timepoints.

For example I am trying to send this SSML text:

`<speak> Hello <mark name='0'/> there. How <mark name='1'/> are you ? <mark name='2'/> </speak>`

But only the first and the third one get the corresponding data:

```
[
  { timeSeconds: 0.36943328380584717, markName: '0' },
  { timeSeconds: 1.465, markName: '2' }
]
```
Am I doing something wrong or is it a known issue?

**Comment by infation** [comment]
I figured that using WaveNet voices instead of standard ones i.e en-US-Wavenet-C voice instead of en-US-Standard-C actually generated the results that I was looking for. Can this be implemented for standard voices as well ?

**Comment by munkhuushmgl** [comment]
@infation I will request this feature internally, but cannot give you estimate time response due to holidays.
