### ISSUE TITLE
Running npm install in Windows Causes errors.

### ISSUE THREAD

**Issue by samcodee** [googleapis/nodejs-text-to-speech#545]
When I cloned this repo and ran ```npm i```, it caused an error like this:
<img width="629" alt="Error TTS" src="https://user-images.githubusercontent.com/62462363/130647150-210fecc2-7866-4352-943c-c8de8f8feac8.png">

It worked perfectly fine in a Mac though. 

1) Is this a client library issue or a product issue?
 Client Library

2) Did someone already solve this?
  No

3) Do you have a support contract?
 No

#### Environment details

  - OS: Windows 10 (21H1 OS Build 19043.1151)
  - Node.js version: 12.13.1
  - npm version: 6.12.1
  - `@google-cloud/text-to-speech` version: 3.3.0

#### Steps to reproduce

  1.  Clone this repository by downloading zip file.
  2. Extract the zip file.
  3. Run ```npm i```
 
Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @samcodee — thank you for filing this issue. I was unable to repo this issue on my local Windows machine. Maybe you want to troubleshoot for any potential issues with your ```npm``` installation.

**Comment by samcodee** [comment]
@b-loved-dreamer - I checked my npm installation. I have updated it. It does work. Might be a previous npm issue or my npm installation. Thanks. Closing this issue
