### ISSUE TITLE
Native ES Module Support

### ISSUE THREAD

**Issue by bradocchs** [googleapis/nodejs-text-to-speech#547]
I've tried using this package as a module in Vite, but it fails with:
```
Module "stream" has been externalized for browser compatibility and cannot be accessed in client code.
```
I assume this is because this package currently only works as CJS not ESM. If I'm correct, any plans to support ESM? If I'm wrong, how can I get this working in Vite project?

Currently importing like so:
```
import { TextToSpeechClient } from '@google-cloud/text-to-speech'
```

Thanks for any advice.

**Comment by bradocchs** [comment]
UPDATE: For fun I tried using native import outside the browser and it worked fine. So will this package only work server-side? If so, are there any plans for a javascript client library?

**Comment by telpirion** [comment]
Hi @bradocchs , currently this package is only intended for use server-side. There aren't any current plans to use it client-side.
