### ISSUE TITLE
using ssml_mark is not returning the timepoints information

### ISSUE THREAD

**Issue by alexyoux** [googleapis/nodejs-text-to-speech#560]
As mentioned in the docs, the timepoints were supposed to return. But I got no luck getting the info.

The Text-to-Speech API supports the use of timepoints in your created audio data. A timepoint is a timestamp (in seconds, measured from the beginning of the generated audio) that corresponds to a designated point in the script. You can set a timepoint in your script using the <mark> tag. When the audio is generated, the API then returns the time offset between the beginning of the audio and the timepoint.

There are two steps to setting a timepoint:

Add a <mark> SSML tag to the point in the script that you want a timestamp for.
Set TimepointType to SSML_MARK. If this field is not set, timepoints are not returned by default.

I have done all the steps but the timepoints info is not returned in the result.
```
  const request = {
    input: {text: fs.readFileSync(textFile)},
    voice: {languageCode: 'en-US', ssmlGender: 'FEMALE'},
    audioConfig: {audioEncoding: 'MP3'},
    enableTimePointing: ['SSML_MARK']
  };

  const [response] = await client.synthesizeSpeech(request);
```
<img width="791" alt="Screen Shot 2021-11-09 at 3 30 40 pm" src="https://user-images.githubusercontent.com/41031170/140862479-2bdbfb5b-12c0-4640-9e96-a88a1a2f64dd.png">

A similar issue has been reported before. 
https://github.com/googleapis/nodejs-text-to-speech/issues/410

**Comment by b-loved-dreamer** [comment]
Hi @alexyoux — thank you for filing this issue. To be able to get ```timepoint``` information, you need to add the ```<mark>``` to your input, like [so](https://cloud.google.com/text-to-speech/docs/ssml#example_4). You also need to use the ```v1beta1``` version of the API: ```const textToSpeech = require('@google-cloud/text-to-speech').v1beta1;```.

**Comment by alexyoux** [comment]
Hi @b-loved-dreamer 


It works. I should use v1beta1. Thanks for your help. 

<img width="794" alt="Screen Shot 2021-11-10 at 1 05 50 pm" src="https://user-images.githubusercontent.com/41031170/141036304-31e1763b-5f26-476e-9346-4353481afcf3.png">
