### ISSUE TITLE
Update to "node-fetch": "^2.6.7"

### ISSUE THREAD

**Issue by XavierJordaMurria** [googleapis/nodejs-text-to-speech#646]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
the current version used for node-fetch has a vulnerability.
[https://snyk.io/vuln/SNYK-JS-NODEFETCH-2342118]

 **Describe the solution you'd like**
you should update to the fixing version node-fetch:2.6.7 like you already did in the google-gax:3.3.0 
 **Describe alternatives you've considered**
 **Additional context**

**Comment by sofisl** [comment]
This should be using the [latest version](https://github.com/googleapis/gax-nodejs/blob/d3d85c0939c0d00f15b0eaa30bc2fb6e5c12d656/package.json#L26) of node-fetch.
