### ISSUE TITLE
TypeError: Cannot convert undefined or null to object - on basic installation

### ISSUE THREAD

**Issue by mahaguru24** [googleapis/nodejs-text-to-speech#74]
#### Environment details

  - OS: MAC Osx
  - Node.js version: 8.5.0
  - npm version:
  - `@google-cloud/text-to-speech` version: ^0.3.0

#### Steps to reproduce

  1. Create react app with create-react-app
  2. Follow basic tutorial for @google-cloud/text-to-speech

```
TypeError: Cannot convert undefined or null to object
./node_modules/globby/node_modules/pify/index.js.module.exports
node_modules/globby/node_modules/pify/index.js:75
  72 | 		return processFn(obj, opts).apply(this, arguments);
  73 | 	};
  74 | } else {
 75 | 	ret = Object.create(Object.getPrototypeOf(obj));
  76 | }
  77 | 
  78 | for (const key in obj) { // eslint-disable-line guard-for-in
```
gets the above error
Following these steps will guarantee the quickest resolution possible.

I am new in React, can you please let me know how to resolve this error ?

Thanks!

**Comment by stephenplusplus** [comment]
Unfortunately, we do not have explicit support for React at this time. You can keep an eye on this issue, should this change: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/531
