### ISSUE TITLE
Api seems not to work on Raspbian/Raspberry Pi Zero W

### ISSUE THREAD

**Issue by Hugo54** [googleapis/nodejs-text-to-speech#77]
#### Environment details

  - COMPUTER : 
Raspberry PI Zero W
  - OS: 
RASPBIAN STRETCH LITE
Minimal image based on Debian Stretch
Version:June 2018
Release date:2018-06-27
Kernel version:4.14
  - Node.js version:
*/pi@raspberrypi:~/testnode $ node -v
v8.11.4
  - npm version:
pi@raspberrypi:~/testnode $ npm -v
5.6.0
  - `@google-cloud/text-to-speech` version:
"@google-cloud/text-to-speech": "^0.3.0"

#### Steps to reproduce

1. I create an env variable with my google credential path : GOOGLE_APPLICATION_CREDENTIALS="my path to json credential". The json file I use also on my windows machine.
2. I create project with "npm init"
3. I Install the last text-to-speech depency with "npm install"
4. I create a file index.js 
// Imports the Google Cloud client library
const textToSpeech = require('@google-cloud/text-to-speech');
// Creates a client
const client = new textToSpeech.TextToSpeechClient();
4. When I execute index.js I get (with or without sudo)
pi@raspberrypi:~/testnode $ node index.js
Illegal instruction

Any Idea ? It seems to fail on the TextToSpeechClient().

Best regards,

Hugo

**Comment by mtalebi** [comment]
Making an http request was my workaround as well. :/

**Comment by JustinBeckwith** [comment]
With our recent switch to grpc-js, I'm reasonably confident this should be fixed :) Please do let us know if you're still running into any issues!
