### ISSUE TITLE
Cannot find module 'text-to-speech'

### ISSUE THREAD

**Issue by mrwnmonm** [googleapis/nodejs-text-to-speech#9]
Getting ```Cannot find module 'text-to-speech'``` error.

#### Environment details
  - OS: Ubuntu 16.04 64bit
  - Node.js version: 6.3.0
  - npm version: 3.10.3
  - `text-to-speech` version: 1.0.8

#### Steps to reproduce
  1. ```npm install --save text-to-speech```
  2. ``` ... = require(text-to-speech')```
  3. ```node <file>```

**Comment by niravpatel2008** [comment]
Uninstall existing text-to-speech which is not actual google official.

Try blow cmd to install text-to-speech:

`npm install --save googleapis/nodejs-text-to-speech`

Use as below:

`var tts = require('@google-cloud/text-to-speech');`


Hope this will help you to start :)

**Comment by MumblesNZ** [comment]
Shouldn't the documentation be updated to reflect this?

**Comment by JustinBeckwith** [comment]
Greetings!  It was addressed in #4
