### ISSUE TITLE
Highlighting text as the audio is being played

### ISSUE THREAD

**Issue by rrrepos** [googleapis/nodejs-text-to-speech#96]
I am using the Google Cloud Text-to-Speech API to convert some dynamic text and send the response to the browser. I have been successful in doing it, by sending the audio response as a base64 string and playing it using:

````
let audio = document.querySelector('audio');
audio.src = base64str;
audio.play();
````

Is there a way in which I can highlight the text as the voice is being spoken? The response from the server contains both the voice as well as the text from this the T2S was done. Thanks

**Comment by JustinBeckwith** [comment]
@beccasaurus & @googleapis/ml-apis can y'all take a look?

**Comment by nnegrey** [comment]
Hi, this is pretty intriguing, at the moment I don't think we have any guides on how to do this, but it seems like you are looking for a [VTT](https://www.w3.org/wiki/VTT_Concepts) type of audio file, is that correct?

At the moment, I think you have to create that yourself. This package [node-webvtt](https://www.npmjs.com/package/node-webvtt) might be helpful in that creation though I have never used it. 

Let me know if that helps! :)

**Comment by rrrepos** [comment]
Thanks @nnegrey : Will look into the suggested package. But coming from the education domain where I have spent a few decades a feature like this would perhaps be a default need when using TTS. Thanks.

**Comment by jasan-s** [comment]
@rrrepos did you find a solution to this? If so please share.

**Comment by nicolehe** [comment]
@rrrepos @jasan-s also curious if you found a solution!

**Comment by rrrepos** [comment]
No. have not worked on it since
